### ISSUE TITLE
Zen browser cannot load themes in the store page

### ISSUE THREAD

**Issue by rivenirvana** [zen-browser/theme-store#164]
Freshly installed Zen browser (flathub says 1.0.0-a.15 but browser settings says 1.0.0-a.28) does not load the theme entries in https://www.zen-browser.app/themes (says CORS failed), while regular Firefox (v129.0.2) can. Cleared all data, disabled cache, themes not popping up.

![image](https://github.com/user-attachments/assets/e6307cc4-40e5-4ae5-9b52-879101b67e40)

**Comment by NOCanoa** [comment]
huh why is cors poping in ☠️

**Comment by NOCanoa** [comment]
can u try control + shift + r ?

**Comment by rivenirvana** [comment]
Still doesn't show themes.

**Comment by rivenirvana** [comment]
Tried zen-specific AppImage, doesn't show themes as well. Chrome and GNOME Web shows them.

**Comment by rivenirvana** [comment]
I've been considering that this is an issue on my end, I've tried different stuff to no avail, like disabling/enabling DoT and DNSSEC, but then again it loads reliably on other browsers except Zen. And this is default Zen settings, though changing https and dns settings from within Zen did not get me anywhere, either.

What's weird is that when I delete and refresh my config/profile by deleting `~/.zen` or `~/.var/app/io.github.zen_browser.zen`, the themes store site loads properly for a while then doesn't after 2~3 application restarts.

**Comment by rivenirvana** [comment]
This issue is really inconsistent and the actual conditions are unclear, but clearing site data proves to be a workaround. I can't really spend much time on this, but since it's not a critical issue, and since it looks to be just an issue on my end and is not easily reproducible, I'll be closing this issue and keep watch of the application's development for now.
