### ISSUE TITLE
[create-theme]: Nord

### ISSUE THREAD

**Issue by giuli635** [zen-browser/theme-store#187]
### Name

Nord

### Description

Unofficial nord theme for Zen Browser

### Homepage

https://www.nordtheme.com/

### Image

https://github.com/nordtheme/visual-studio-code/blob/develop/assets/extension-marketplace-icon-2x.png?raw=true

### Type

- [X] JSON Color Theme

### Theme Styles

```css
{
    "isDarkMode": true,
    "primaryColor": "#5e81ac",
    "secondaryColor": "#4c566a",
    "tertiaryColor": "#3b4252",
    "colorsBorder": "#4c566a",
    "dialogBg": "#2e3440"
}
```

### Readme

```markdown
Nord theme for Zen Browser
```

**Comment by Bad3r** [comment]
It was rejected due to:

https://github.com/zen-browser/theme-store/pull/188#issuecomment-2351527336
