### ISSUE TITLE
Theme store doesn't work

### ISSUE THREAD

**Issue by lorebored** [zen-browser/theme-store#209]
I can't open any theme page because it gave me 404 error.

![Schermata del 2024-08-27 16-50-07](https://github.com/user-attachments/assets/e1878a41-8752-4e63-958d-2b544d63a62a)
![Schermata del 2024-08-27 16-50-12](https://github.com/user-attachments/assets/78a0b094-c065-474e-9501-c327f0ab5911)

**Comment by mauro-balades** [comment]
Try now 👍🏽
