### ISSUE TITLE
Installed Themes section

### ISSUE THREAD

**Issue by slrgt** [zen-browser/theme-store#264]
Would it be possible to include a filter on the Theme Store so we can click it and see only the themes we have installed? It would be very convenient for when we want to go back to default or uninstall themes that might conflict with eachother

**Comment by NOCanoa** [comment]
btw u can uninstall themes in setting page `about:preferences#zenMarketplace`

**Comment by n7itro** [comment]
> Yes, but it took me some time to figure that out because the themes only show up after refreshing the themes page in settings

This should be fixed on the latest version

**Comment by slrgt** [comment]
How will any regular user find out that exists though? It would be really helpful to have a filter on the theme store
