### ISSUE TITLE
How can I test the preferences.json file I'm working on?

### ISSUE THREAD

**Issue by HliasOuzounis** [zen-browser/theme-store#554]
I'm trying to add a preferences.json file to my theme (better active tab) to allow the user to select whether the active tab indicator is on the right or on the left. I'm testing it with a preferences.json file that I add to my folder in .config/zen/chrome/zen-themes/... but I don't see the option when I open the browser, not even the gear icon. 

The preferences file looks like this:
```javascript
{
    "property": "theme.better-active-tab.on-right",
    "label": "Move tha active tab indicator to the right",
    "type": "checkbox"
}
``` 
Should I just create a pull request to the theme-store with the changes? I'd like to test that it works before that.

**Comment by Dinno-DEV** [comment]
Make sure you encase it again with another curlies {}, I've made a mistake of not doing that
```
{
  {
      "property": "theme.better-active-tab.on-right",
      "label": "Move tha active tab indicator to the right",
      "type": "checkbox"
  }
}

**Comment by HliasOuzounis** [comment]
Thanks, that was one piece of the puzzle. To get the options on the browser though, I had to edit the `zen-themes.json` file in `~/.config/zen` and manually add the preferences file to the respective entry in the json.
