### ISSUE TITLE
[bug] hide window buttons

### ISSUE THREAD

**Issue by nkapila6** [zen-browser/theme-store#57]
This theme does not work. 

I'm currently on macOS and the picture on the [theme page](https://www.zen-browser.app/themes/5a007026-0801-4a5d-9740-f17dc1c3ff21) looks like it was made for Windows. Could this be a reason?

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/8ba96857-6528-43ff-88ca-56c649f52d62">

**Comment by mauro-balades** [comment]
Are these buttons injected by macos or by Firefox? @n7itro

**Comment by n7itro** [comment]
It seems like MacOS does not allow individually removing the buttons. I suggest we change the themes description to specify it is for Windows (and Linux?) only and add another theme for MacOS.

**Comment by mauro-balades** [comment]
I wonder if it's like native or if it can be inspected though

**Comment by n7itro** [comment]
We would need a mac user to try... It's most likely just one element because I've heard that the following does work for macOS 
`.titlebar-buttonbox-container { display: none }`. For now, I'll create a separate theme for mac

**Comment by nkapila6** [comment]
Yeah, I was going to comment the same thing.

```css
@media (-moz-mac-big-sur-theme: 1) {
  hbox.titlebar-buttonbox-container { display: none !important; }
}
```

This works.

**Comment by n7itro** [comment]
> Yeah, I was going to comment the same thing.
> 
> ```css
> @media (-moz-mac-big-sur-theme: 1) {
>   hbox.titlebar-buttonbox-container { display: none !important; }
> }
> ```
> 
> This works.

I can add this to the theme so it removes the window control buttons automatically for mac users. The options won't do anything on mac though. Thank you!

**Comment by mauro-balades** [comment]
This will be fixed with the addition of https://docs.zen-browser.app/themes-store/themes-marketplace-preferences#operating-system-specific-settings in the next release 👍🏽
